version: 1
frontend:
  phases:
    preBuild:
      commands:
        # Install Node Version Manager for Linux environment (Amplify uses a Linux build container)
        # Then install and use Node 20
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        - export NVM_DIR="$HOME/.nvm"
        - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        - nvm install 20
        - nvm use 20
        - node -v  # Verify Node version is 20.x
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
