apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default
  annotations:
    # No need for SSL redirect when using HTTP only
spec:
  ingressClassName: alb  # or your chosen Ingress controller class
  rules:
    - host: user.betterhealthservices.42web.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
    - host: messaging.betterhealthservices.42web.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: messaging-service
                port:
                  number: 80
    - host: counsellor.betterhealthservices.42web.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: counsellor-service
                port:
                  number: 80
